server:
  port: 8081

spring:
  application:
    name: lab-sso
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: adfasdes034179o3hap0il7ktrv6id7
            client-secret: lP3VACDHji9UmgJr3gEf
          # google:
          #   client-id: 99999999999999999999999999999
          #   client-secret: 99999999999999999999999999
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7081/realms/lab-saml-sp
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

application:
  idp-url: http://localhost:7081/realms/lab-saml-sp/protocol/openid-connect/token
