server:
  port: 8081

spring:
  application:
    name: lab-sso
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7081/realms/lab-saml-sp
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


application:
  idp-url: http://localhost:7081/realms/lab-saml-sp/protocol/openid-connect/token